require "cgi"
require "erb"

def write(path, template, binding)
  File.write(path, ERB.new(template).result(binding))
end

head = <<HTML
<link rel="stylesheet" href="../node_modules/highlight.js/styles/atom-one-dark.css">
<link rel="stylesheet" href="style.css">
HTML

footer = <<HTML
<footer>
  Powered by <a href="https://github.com/utkarshkukreti/bs-preact">bs-preact</a>.
</footer>
HTML

task :default do
  files = FileList["*.ml"].ext("").reject { |file| file.end_with?("_") }

  files.each do |name|
    write "#{name}.html", <<ERB, binding
<!doctype html>
<html>
  <head>
    <title>#{name}</title>
    #{head}
  </head>
  <body>
    <h1>#{name}</h1>
    <main></main>
    <pre><code class="ocaml">#{CGI.escape_html(File.read("#{name}.ml"))}</code></pre>
    #{footer}
    <script src="#{name}.bs.js"></script>
    <script src="highlight.js"></script>
  </body>
</html>
ERB
  end

  write "index.html", <<ERB, binding
<!doctype html>
<html>
  <head>
    <title>Examples</title>
    #{head}
  </head>
  <body>
    <h1>bs-preact Examples</h1>
    <ul>
      <% files.each do |name| %>
        <li>
          <a href="<%= name %>.html"><%= name %></a>
        </li>
      <% end %>
    </ul>
    #{footer}
  </body>
</html>
ERB
end
