// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE


var Animation = 0;

var Clipboard = 0;

var Composition = 0;

var Drag = 0;

var Event = 0;

var Focus = 0;

var Keyboard = 0;

var Mouse = 0;

var Pointer = 0;

var Touch = 0;

var Transition = 0;

var Ui = 0;

var Wheel = 0;

export {
  Animation ,
  Clipboard ,
  Composition ,
  Drag ,
  Event ,
  Focus ,
  Keyboard ,
  Mouse ,
  Pointer ,
  Touch ,
  Transition ,
  Ui ,
  Wheel ,
  
}
/* No side effect */
