// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function fromString(string) {
  var path = Belt_List.fromArray(Belt_Array.keep(string.split("/"), (function (x) {
              return x !== "";
            })));
  return /* record */[/* path */path];
}

var Url = /* module */[/* fromString */fromString];

export {
  Url ,
  
}
/* No side effect */
